# Generated by Django 5.2.5 on 2025-09-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='book',
            name='books_book_languag_2c24ff_idx',
        ),
        migrations.RemoveIndex(
            model_name='chapter',
            name='books_chapt_book_id_8e54c4_idx',
        ),
        migrations.RemoveIndex(
            model_name='chapter',
            name='books_chapt_publish_c4d96b_idx',
        ),
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='status',
        ),
        migrations.AddField(
            model_name='book',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether this book is visible to readers'),
        ),
        migrations.AddField(
            model_name='book',
            name='progress',
            field=models.CharField(choices=[('draft', 'Draft'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='chapter',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether this chapter is visible to readers'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='progress',
            field=models.CharField(choices=[('draft', 'Draft'), ('translating', 'Translating'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='chapter',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='When this chapter should be automatically published', null=True),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['language', 'is_public'], name='books_book_languag_27d3f0_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['is_public', 'progress'], name='books_book_is_publ_a6583d_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['book', 'is_public'], name='books_chapt_book_id_b12b8d_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['is_public', 'progress'], name='books_chapt_is_publ_12a601_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['published_at', 'is_public'], name='books_chapt_publish_c5868a_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['scheduled_at'], name='books_chapt_schedul_9e0308_idx'),
        ),
    ]
