# Generated by Django 5.2.5 on 2025-09-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_books_book_languag_2c24ff_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover image for the book', null=True, upload_to='book_covers/'),
        ),
    ]
