# Generated by Django 5.2.5 on 2025-09-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_books_book_languag_2c24ff_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover image for the book', null=True, upload_to='book_covers/books'),
        ),
        migrations.AddField(
            model_name='bookmaster',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Default cover image for all language versions of this book', null=True, upload_to='book_covers/masters/'),
        ),
        migrations.AddField(
            model_name='language',
            name='count_units',
            field=models.CharField(choices=[('words', 'Words'), ('chars', 'Characters')], default='words', max_length=20),
        ),
    ]
