# Generated by Django 5.2.5 on 2025-09-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_cover_image_bookmaster_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='wpm',
            field=models.PositiveSmallIntegerField(default=400, help_text='Reading speed words per minute'),
        ),
    ]
