# Generated by Django 5.2.5 on 2025-09-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmaster',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Default cover image for all language versions of this book', null=True, upload_to='book_covers/masters/'),
        ),
    ]
