# Generated by Django 5.2.5 on 2025-09-19 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_language_wpm'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(choices=[('character', 'Character'), ('place', 'Place'), ('term', 'Term')], max_length=20)),
                ('source_name', models.CharField(max_length=255)),
                ('translations', models.JSONField(default=dict)),
                ('bookmaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookmaster')),
                ('first_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.chapter')),
            ],
            options={
                'indexes': [models.Index(fields=['bookmaster', 'entity_type'], name='books_booke_bookmas_466fa1_idx')],
                'unique_together': {('bookmaster', 'source_name')},
            },
        ),
        migrations.CreateModel(
            name='ChapterContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key_terms', models.JSONField(default=dict)),
                ('summary', models.TextField(blank=True)),
                ('chapter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.chapter')),
            ],
            options={
                'indexes': [models.Index(fields=['chapter'], name='books_chapt_chapter_238989_idx')],
            },
        ),
    ]
