# Generated by Django 5.2.5 on 2025-09-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_bookentity_chaptercontext'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='translator_notes',
            field=models.TextField(blank=True, help_text='Notes from the translator about assumptions, clarifications, or translation challenges'),
        ),
    ]
