# Generated by Django 5.2.5 on 2025-10-17 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_chapter_translator_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('translations', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='bookmaster',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='book',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether visible to readers'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.language'),
        ),
        migrations.AlterField(
            model_name='bookentity',
            name='bookmaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='books.bookmaster'),
        ),
        migrations.AlterField(
            model_name='bookentity',
            name='first_chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='books.chapter'),
        ),
        migrations.AlterField(
            model_name='bookmaster',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Default cover image for all language versions', null=True, upload_to='book_covers/masters/'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=models.TextField(help_text='Chapter content'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether visible to readers'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='When to publish this chapter automatically', null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='translator_notes',
            field=models.TextField(blank=True, help_text='Notes about assumptions, clarifications, or challenges'),
        ),
        migrations.AlterField(
            model_name='chaptercontext',
            name='chapter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='context', to='books.chapter'),
        ),
        migrations.AlterField(
            model_name='language',
            name='wpm',
            field=models.PositiveSmallIntegerField(default=400, help_text='Reading speed'),
        ),
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order for this genre (lower = first)')),
                ('bookmaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_genres', to='books.bookmaster')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_genres', to='books.genre')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='bookmaster',
            name='genres',
            field=models.ManyToManyField(blank=True, help_text='Book genres/categories', related_name='bookmasters', through='books.BookGenre', to='books.genre'),
        ),
        migrations.AddIndex(
            model_name='bookmaster',
            index=models.Index(fields=['created_at'], name='books_bookm_created_289bdd_idx'),
        ),
        migrations.AddIndex(
            model_name='bookgenre',
            index=models.Index(fields=['bookmaster', 'order'], name='books_bookg_bookmas_ddf56f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookgenre',
            unique_together={('bookmaster', 'genre')},
        ),
    ]
