# Generated by Django 5.2.5 on 2025-10-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_genre_alter_bookmaster_options_alter_book_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='count_format_rules',
            field=models.JSONField(blank=True, default=dict, help_text="Number formatting rules. Example: {6: 'M', 3: 'K'} for English, {8: '亿', 4: '万'} for Chinese"),
        ),
    ]
