# Generated by Django 5.2.5 on 2025-11-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_language_count_format_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmaster',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Hero image for promotion', null=True, upload_to='book_covers/masters/'),
        ),
    ]
