# Generated by Django 5.2.5 on 2025-11-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_bookmaster_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookentity',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
