# Generated by Django 5.2.5 on 2025-11-10 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_bookentity_translations'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStats',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stats', serialize=False, to='books.book')),
                ('total_views', models.BigIntegerField(default=0, help_text='Total number of views (all time)')),
                ('unique_readers_24h', models.IntegerField(default=0, help_text='Unique sessions in last 24 hours')),
                ('unique_readers_7d', models.IntegerField(default=0, help_text='Unique sessions in last 7 days')),
                ('unique_readers_30d', models.IntegerField(default=0, help_text='Unique sessions in last 30 days')),
                ('unique_readers_all_time', models.IntegerField(default=0, help_text='Unique sessions (all time)')),
                ('total_read_time_seconds', models.BigIntegerField(default=0, help_text='Total time spent on this book (seconds)')),
                ('last_viewed_at', models.DateTimeField(blank=True, help_text='Last time this book was viewed', null=True)),
            ],
            options={
                'verbose_name_plural': 'Book stats',
                'indexes': [models.Index(fields=['total_views'], name='books_books_total_v_07058d_idx'), models.Index(fields=['unique_readers_7d'], name='books_books_unique__722c46_idx'), models.Index(fields=['last_viewed_at'], name='books_books_last_vi_df24e7_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChapterStats',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stats', serialize=False, to='books.chapter')),
                ('total_views', models.BigIntegerField(default=0, help_text='Total number of views (all time)')),
                ('unique_views_24h', models.IntegerField(default=0, help_text='Unique sessions in last 24 hours')),
                ('unique_views_7d', models.IntegerField(default=0, help_text='Unique sessions in last 7 days')),
                ('unique_views_30d', models.IntegerField(default=0, help_text='Unique sessions in last 30 days')),
                ('unique_views_all_time', models.IntegerField(default=0, help_text='Unique sessions (all time)')),
                ('total_read_time_seconds', models.BigIntegerField(default=0, help_text='Total time spent reading this chapter (seconds)')),
                ('completion_count', models.IntegerField(default=0, help_text='Number of times readers reached the end')),
                ('last_viewed_at', models.DateTimeField(blank=True, help_text='Last time this chapter was viewed', null=True)),
            ],
            options={
                'verbose_name_plural': 'Chapter stats',
                'indexes': [models.Index(fields=['total_views'], name='books_chapt_total_v_36d839_idx'), models.Index(fields=['unique_views_7d'], name='books_chapt_unique__d454ee_idx'), models.Index(fields=['last_viewed_at'], name='books_chapt_last_vi_0a754e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ViewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('session_key', models.CharField(help_text='Django session ID for anonymous user tracking', max_length=40)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, help_text='When this view occurred')),
                ('read_duration_seconds', models.IntegerField(blank=True, help_text='Time spent reading (updated by JavaScript)', null=True)),
                ('completed', models.BooleanField(default=False, help_text='Whether user scrolled to end of content')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device information', null=True)),
                ('referrer', models.URLField(blank=True, help_text='Previous page URL (traffic source)', max_length=500, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id', 'viewed_at'], name='books_viewe_content_894749_idx'), models.Index(fields=['viewed_at'], name='books_viewe_viewed__8744f2_idx'), models.Index(fields=['session_key', 'viewed_at'], name='books_viewe_session_e578fa_idx')],
            },
        ),
    ]
