# Generated by Django 5.2.5 on 2025-11-12 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_analysisjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translationjob',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='translationjob',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='translationjob',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_jobs', to='books.chapter'),
        ),
        migrations.AddIndex(
            model_name='translationjob',
            index=models.Index(fields=['chapter', 'status'], name='books_trans_chapter_940f6f_idx'),
        ),
    ]
