# Generated by Django 5.2.5 on 2025-11-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_add_created_by_to_analysisjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Whether this language is visible to readers in the reader app'),
        ),
        migrations.AddIndex(
            model_name='language',
            index=models.Index(fields=['is_public'], name='books_langu_is_publ_838f45_idx'),
        ),
    ]
