# Generated by Django 5.2.5 on 2025-11-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_add_language_is_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['code']},
        ),
        migrations.AddIndex(
            model_name='language',
            index=models.Index(fields=['code'], name='books_langu_code_e21f97_idx'),
        ),
    ]
