# Generated by Django 5.2.5 on 2025-11-14 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_language_ordering_and_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Tag name (e.g., 'Female Lead', 'System')", max_length=50, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', unique=True)),
                ('category', models.CharField(choices=[('protagonist', 'Protagonist Type'), ('narrative', 'Narrative Style'), ('theme', 'Theme'), ('trope', 'Trope'), ('content_warning', 'Content Warning'), ('audience', 'Target Audience'), ('setting', 'Setting')], help_text='Category for organizing tags', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description of this tag')),
                ('translations', models.JSONField(blank=True, default=dict, help_text='Localized names and descriptions. Format: {language_code: {name, description}}')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['section', '-is_primary', 'name']},
        ),
        migrations.AddField(
            model_name='genre',
            name='color',
            field=models.CharField(blank=True, help_text="Hex color code for UI styling (e.g., '#FF5733')", max_length=7),
        ),
        migrations.AddField(
            model_name='genre',
            name='icon',
            field=models.CharField(blank=True, help_text="FontAwesome icon class (e.g., 'fa-heart')", max_length=50),
        ),
        migrations.AddField(
            model_name='genre',
            name='is_primary',
            field=models.BooleanField(default=True, help_text='Primary genres appear in main navigation; sub-genres are refinements'),
        ),
        migrations.AddField(
            model_name='genre',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent genre (only for sub-genres)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_genres', to='books.genre'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True, help_text='Description of this genre'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Genre name (can repeat across sections)', max_length=50),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(help_text='URL-friendly identifier (unique within section)'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text='Localized names and descriptions. Format: {language_code: {name, description}}'),
        ),
        migrations.CreateModel(
            name='BookKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keyword', models.CharField(db_index=True, help_text='The searchable keyword', max_length=255)),
                ('keyword_type', models.CharField(choices=[('section', 'Section'), ('genre', 'Genre'), ('tag', 'Tag'), ('entity_character', 'Character'), ('entity_place', 'Place'), ('entity_term', 'Term')], help_text='Type of keyword for filtering', max_length=20)),
                ('language_code', models.CharField(help_text='Language of this keyword', max_length=10)),
                ('weight', models.FloatField(default=1.0, help_text='Relevance weight for ranking (higher = more relevant)')),
                ('bookmaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='books.bookmaster')),
            ],
        ),
        migrations.CreateModel(
            name='BookTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confidence', models.FloatField(default=1.0, help_text='Confidence score for AI-suggested tags (0.0-1.0)')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('ai_suggested', 'AI Suggested'), ('ai_auto', 'AI Automatic'), ('community', 'Community')], default='manual', help_text='Source of this tag assignment', max_length=20)),
                ('bookmaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_tags', to='books.bookmaster')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Section name (e.g., 'Fiction', 'BL', 'GL')", max_length=50, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this section')),
                ('icon', models.CharField(blank=True, help_text="FontAwesome icon class (e.g., 'fa-book')", max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order (lower = first)')),
                ('is_mature', models.BooleanField(default=False, help_text='Whether this section contains mature content requiring age verification')),
                ('translations', models.JSONField(blank=True, default=dict, help_text='Localized names and descriptions. Format: {language_code: {name, description}}')),
            ],
            options={
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['order'], name='books_secti_order_154dd6_idx'), models.Index(fields=['slug'], name='books_secti_slug_0802ee_idx')],
            },
        ),
        migrations.AddField(
            model_name='bookmaster',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Content section (Fiction, BL, GL, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookmasters', to='books.section'),
        ),
        migrations.AddField(
            model_name='genre',
            name='section',
            field=models.ForeignKey(blank=True, help_text='The section this genre belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='books.section'),
        ),
        migrations.AlterUniqueTogether(
            name='genre',
            unique_together={('section', 'slug')},
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['section', 'is_primary'], name='books_genre_section_fcecf7_idx'),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['section', 'slug'], name='books_genre_section_5d1d12_idx'),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['parent'], name='books_genre_parent__d3be48_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['category'], name='books_tag_categor_bad087_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['slug'], name='books_tag_slug_be145c_idx'),
        ),
        migrations.AddField(
            model_name='booktag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_tags', to='books.tag'),
        ),
        migrations.AddField(
            model_name='bookmaster',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Book tags (protagonist type, tropes, themes, etc.)', related_name='bookmasters', through='books.BookTag', to='books.tag'),
        ),
        migrations.AddIndex(
            model_name='bookkeyword',
            index=models.Index(fields=['keyword', 'keyword_type'], name='books_bookk_keyword_accb37_idx'),
        ),
        migrations.AddIndex(
            model_name='bookkeyword',
            index=models.Index(fields=['bookmaster', 'keyword_type'], name='books_bookk_bookmas_06a93d_idx'),
        ),
        migrations.AddIndex(
            model_name='bookkeyword',
            index=models.Index(fields=['language_code', 'keyword'], name='books_bookk_languag_ab6724_idx'),
        ),
        migrations.AddIndex(
            model_name='booktag',
            index=models.Index(fields=['bookmaster', 'source'], name='books_bookt_bookmas_ff1ddf_idx'),
        ),
        migrations.AddIndex(
            model_name='booktag',
            index=models.Index(fields=['tag'], name='books_bookt_tag_id_66f000_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='booktag',
            unique_together={('bookmaster', 'tag')},
        ),
    ]
