# Generated by Django 5.2.5 on 2025-11-14 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_tag_alter_genre_options_genre_color_genre_icon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookkeyword',
            options={'verbose_name': 'Book Keyword', 'verbose_name_plural': '📚 Taxonomy - Keywords (Search Index)'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['section', '-is_primary', 'name'], 'verbose_name': 'Genre', 'verbose_name_plural': '📚 Taxonomy - Genres'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Section', 'verbose_name_plural': '📚 Taxonomy - Sections'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Tag', 'verbose_name_plural': '📚 Taxonomy - Tags'},
        ),
    ]
