# Generated by Django 5.2.5 on 2025-11-14 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_alter_bookkeyword_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisjob',
            options={'ordering': ['-created_at'], 'verbose_name': 'Analysis Job', 'verbose_name_plural': 'Jobs - Analysis Jobs'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at'], 'verbose_name': 'Book', 'verbose_name_plural': 'Core - Books'},
        ),
        migrations.AlterModelOptions(
            name='bookentity',
            options={'verbose_name': 'Book Entity', 'verbose_name_plural': 'Context - Book Entities'},
        ),
        migrations.AlterModelOptions(
            name='bookkeyword',
            options={'verbose_name': 'Book Keyword', 'verbose_name_plural': 'Taxonomy - Keywords'},
        ),
        migrations.AlterModelOptions(
            name='bookmaster',
            options={'ordering': ['-created_at'], 'verbose_name': 'Book Master', 'verbose_name_plural': 'Core - Book Masters'},
        ),
        migrations.AlterModelOptions(
            name='bookstats',
            options={'verbose_name': 'Book Stats', 'verbose_name_plural': 'Statistics - Book Stats'},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name': 'Chapter', 'verbose_name_plural': 'Core - Chapters'},
        ),
        migrations.AlterModelOptions(
            name='chaptercontext',
            options={'verbose_name': 'Chapter Context', 'verbose_name_plural': 'Context - Chapter Contexts'},
        ),
        migrations.AlterModelOptions(
            name='chaptermaster',
            options={'ordering': ['chapter_number'], 'verbose_name': 'Chapter Master', 'verbose_name_plural': 'Core - Chapter Masters'},
        ),
        migrations.AlterModelOptions(
            name='chapterstats',
            options={'verbose_name': 'Chapter Stats', 'verbose_name_plural': 'Statistics - Chapter Stats'},
        ),
        migrations.AlterModelOptions(
            name='fileuploadjob',
            options={'ordering': ['-created_at'], 'verbose_name': 'File Upload Job', 'verbose_name_plural': 'Jobs - File Upload Jobs'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['section', '-is_primary', 'name'], 'verbose_name': 'Genre', 'verbose_name_plural': 'Taxonomy - Genres'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['code'], 'verbose_name': 'Language', 'verbose_name_plural': 'Core - Languages'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Section', 'verbose_name_plural': 'Taxonomy - Sections'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Taxonomy - Tags'},
        ),
        migrations.AlterModelOptions(
            name='translationjob',
            options={'ordering': ['-created_at'], 'verbose_name': 'Translation Job', 'verbose_name_plural': 'Jobs - Translation Jobs'},
        ),
        migrations.AlterModelOptions(
            name='viewevent',
            options={'ordering': ['-viewed_at'], 'verbose_name': 'View Event', 'verbose_name_plural': 'Statistics - View Events'},
        ),
    ]
