# Generated by Django 5.2.5 on 2025-11-20 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_populate_book_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='color',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='section',
            name='icon',
        ),
    ]
