# Generated by Django 5.2.5 on 2025-11-21 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0022_remove_genre_color_remove_genre_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True, help_text='Description or details'),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, help_text='Description or details'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, help_text='Description or details'),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, help_text='Description or details')),
                ('translations', models.JSONField(blank=True, default=dict, help_text='Localized names and descriptions. Format: {language_code: {name, description}}')),
                ('name', models.CharField(help_text="Author's canonical name", max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=100, unique=True)),
                ('avatar', models.ImageField(blank=True, help_text='Author profile image', null=True, upload_to='authors/')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Taxonomy - Authors',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='books_autho_slug_b44f85_idx'), models.Index(fields=['name'], name='books_autho_name_5aec2d_idx')],
            },
        ),
        migrations.AddField(
            model_name='bookmaster',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Original author of the work', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookmasters', to='books.author'),
        ),
    ]
