# Generated by Django 5.2.5 on 2025-11-21 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0023_add_author_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookentity',
            name='last_chapter',
            field=models.ForeignKey(blank=True, help_text='Most recent chapter where entity appears', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_entities', to='books.chapter'),
        ),
        migrations.AddField(
            model_name='bookentity',
            name='occurrence_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of chapters this entity appears in'),
        ),
        migrations.AlterField(
            model_name='bookentity',
            name='first_chapter',
            field=models.ForeignKey(help_text='Chapter where entity first appears', on_delete=django.db.models.deletion.CASCADE, related_name='new_entities', to='books.chapter'),
        ),
        migrations.AlterField(
            model_name='bookkeyword',
            name='keyword_type',
            field=models.CharField(choices=[('section', 'Section'), ('genre', 'Genre'), ('tag', 'Tag'), ('entity_character', 'Character'), ('entity_place', 'Place'), ('entity_term', 'Term'), ('title', 'Title'), ('author', 'Author')], help_text='Type of keyword for filtering', max_length=20),
        ),
        migrations.AddIndex(
            model_name='bookentity',
            index=models.Index(fields=['occurrence_count'], name='books_booke_occurre_e75340_idx'),
        ),
    ]
