# Generated by Django 5.2.5 on 2025-11-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0024_add_entity_occurrence_tracking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['section', '-is_primary', 'order', 'name'], 'verbose_name': 'Genre', 'verbose_name_plural': 'Taxonomy - Genres'},
        ),
        migrations.AddField(
            model_name='genre',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Display order (lower numbers appear first)'),
        ),
    ]
