# Generated by Django 5.2.5 on 2025-11-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0025_alter_genre_options_genre_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookentity',
            options={'ordering': ['order', 'source_name'], 'verbose_name': 'Book Entity', 'verbose_name_plural': 'Context - Book Entities'},
        ),
        migrations.AddField(
            model_name='bookentity',
            name='order',
            field=models.PositiveSmallIntegerField(default=999, help_text='Display order (lower numbers appear first)'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='order',
            field=models.PositiveSmallIntegerField(default=999, help_text='Display order (lower numbers appear first)'),
        ),
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.PositiveSmallIntegerField(default=999, help_text='Display order (lower numbers appear first)'),
        ),
        migrations.AddIndex(
            model_name='bookentity',
            index=models.Index(fields=['order'], name='books_booke_order_1e3837_idx'),
        ),
    ]
