"""
Django settings for myapp project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables
if os.getenv("RAILWAY_ENVIRONMENT"):
    # On Railway, use environment variables directly
    pass
else:
    # Local development
    load_dotenv(BASE_DIR.parent / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY", "django-insecure-development-secret-key-change-in-production"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "FALSE") == "True"

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")

CSRF_TRUSTED_ORIGINS = [f"https://{os.getenv('RAILWAY_PUBLIC_DOMAIN')}"]

# Application definition

INSTALLED_APPS = [
    # Custom user model first
    "accounts.apps.AccountsConfig",
    # Django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "django.contrib.sitemaps",  # For SEO sitemaps
    # Third party - minimal
    "crispy_forms",
    "crispy_bootstrap5",
    "storages",
    "django_celery_beat",
    # Development tools
    "debug_toolbar",
    # i18n management
    "rosetta",
    # Local apps - simplified
    "books.apps.BooksConfig",
    "reader.apps.ReaderConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",  # Debug toolbar - early in middleware stack
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "books.middleware.StatsTrackingMiddleware",  # Stats tracking
]

ROOT_URLCONF = "myapp.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "books.context_processors.breadcrumb_context",
                "books.context_processors.stats_context",
            ],
        },
    },
]

WSGI_APPLICATION = "myapp.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database configuration
if os.getenv("DATABASE_URL"):
    # Railway/Production provides DATABASE_URL
    import dj_database_url

    DATABASES = {"default": dj_database_url.parse(os.getenv("DATABASE_URL"))}
else:
    # Development - SQLite
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = "static/"
# STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise configuration for static files
# STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media files configuration
if os.getenv("AWS_ACCESS_KEY_ID"):
    # Production - use S3
    AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME")
    AWS_S3_FILE_OVERWRITE = False
    AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3StaticStorage",
            "OPTIONS": {
                "location": "media",
            },
        },
        "staticfiles": {
            "BACKEND": "storages.backends.s3boto3.S3StaticStorage",
            "OPTIONS": {
                "location": "static",
            },
        },
    }

else:
    # Development - local storage
    MEDIA_URL = "media/"
    MEDIA_ROOT = BASE_DIR / "media"

    STATIC_URL = "static/"
    STATIC_ROOT = BASE_DIR / "staticfiles"
    # WhiteNoise configuration for static files
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# OpenAI settings
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")

# AI Model Configuration (using GPT-4o-mini for both analysis and translation)
# GPT-4o-mini provides: 128K context window, 16K max output tokens, better performance, lower cost
AI_MODEL = "gpt-4o-mini"

# Analysis Service Settings
ANALYSIS_MODEL = AI_MODEL
ANALYSIS_MAX_TOKENS = 2000  # Sufficient for entity extraction JSON
ANALYSIS_TEMPERATURE = 0.1  # Low temperature for consistent structured output

# Translation Service Settings
TRANSLATION_MODEL = AI_MODEL
TRANSLATION_MAX_TOKENS = 16000  # Increased from 4000 - GPT-4o-mini supports up to 16K output
TRANSLATION_TEMPERATURE = 0.3  # Slightly higher for more natural translations

# Login/Logout
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/accounts/login/"

# Custom User Model
AUTH_USER_MODEL = "accounts.User"

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Logging configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "translation": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}

# Add file logging only in development (when logs directory exists)
if DEBUG and (BASE_DIR / "logs").exists():
    LOGGING["handlers"]["file"] = {
        "class": "logging.FileHandler",
        "filename": BASE_DIR / "logs" / "django.log",
        "formatter": "verbose",
    }
    LOGGING["handlers"]["translation_file"] = {
        "class": "logging.FileHandler",
        "filename": BASE_DIR / "logs" / "translation.log",
        "formatter": "verbose",
    }
    LOGGING["loggers"]["django"]["handlers"] = ["file", "console"]
    LOGGING["loggers"]["translation"]["handlers"] = ["translation_file", "console"]

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB

# Production security settings
if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

    # Railway proxy settings for CSRF
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True
    USE_X_FORWARDED_PORT = True


# Featured Books and Genres
FEATURED_BOOKS = [int(x) for x in os.getenv("FEATURED_BOOKS", "").split(",") if x.strip()]
FEATURED_GENRES = [int(x) for x in os.getenv("FEATURED_GENRES", "").split(",") if x.strip()]

# ==============================================================================
# REDIS & CACHING CONFIGURATION
# ==============================================================================

# Enable/disable caching (useful for development)
# Set DISABLE_CACHE=True in .env to use Django's dummy cache (no caching)
CACHE_ENABLED = os.getenv('DISABLE_CACHE', 'False').lower() != 'true'

# Redis URL from environment
REDIS_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/0')

# Cache configuration
if CACHE_ENABLED:
    # Production: Use Redis cache
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'SOCKET_CONNECT_TIMEOUT': 5,
                'SOCKET_TIMEOUT': 5,
                'RETRY_ON_TIMEOUT': True,
                'CONNECTION_POOL_KWARGS': {
                    'max_connections': 50,
                    'retry_on_timeout': True,
                },
                # HiredisParser is optional and requires hiredis package
                # If hiredis is installed, django-redis will use it automatically
                # 'PARSER_CLASS': 'redis.connection.HiredisParser',  # Removed - not needed
            },
            'KEY_PREFIX': 'webnovel',
            'TIMEOUT': 300,  # Default cache timeout (5 minutes)
        }
    }
else:
    # Development: Use dummy cache (no caching, always hits database)
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
        }
    }
    print("⚠️  Cache disabled - using DummyCache backend (all cache calls will hit the database)")

# Session storage using Redis (optional, for better performance)
# SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
# SESSION_CACHE_ALIAS = 'default'

# Cache timeout durations (in seconds)
# These can be tuned for production performance based on data change frequency
CACHE_TIMEOUT_STATIC_DATA = 3600        # 1 hour - Languages, genres (rarely change, admin-only)
CACHE_TIMEOUT_METADATA = 1800           # 30 minutes - Chapter counts, book stats (updates on publish)
CACHE_TIMEOUT_CONTENT_LIST = 900        # 15 minutes - Book lists, featured books, carousels
CACHE_TIMEOUT_HOMEPAGE = 600            # 10 minutes - Homepage sections (high traffic, balance freshness)
CACHE_TIMEOUT_NAVIGATION = 1800         # 30 minutes - Chapter navigation (updates when new chapters added)

# ==============================================================================
# CELERY CONFIGURATION
# ==============================================================================

# Celery Broker (Redis)
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', REDIS_URL)

# Celery Result Backend (Redis)
CELERY_RESULT_BACKEND = REDIS_URL

# Celery Task Serialization
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Celery Timezone
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

# Celery Task Configuration
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes max per task
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutes soft limit

# Celery Worker Configuration
CELERY_WORKER_PREFETCH_MULTIPLIER = 4
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000  # Restart worker after 1000 tasks

# Celery Beat (Scheduler) Configuration
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Celery Result Backend Settings
CELERY_RESULT_EXPIRES = 3600  # Results expire after 1 hour

# Job Processing Concurrency Limits
# Global limit across all job types to manage hardware resources
JOB_PROCESSING_GLOBAL_LIMIT = int(os.getenv('JOB_PROCESSING_GLOBAL_LIMIT', 6))

# Individual job type limits (must sum to <= global limit)
JOB_PROCESSING_TRANSLATION_LIMIT = int(os.getenv('JOB_PROCESSING_TRANSLATION_LIMIT', 1))  # Sequential
JOB_PROCESSING_ANALYSIS_LIMIT = int(os.getenv('JOB_PROCESSING_ANALYSIS_LIMIT', 3))  # Parallel
JOB_PROCESSING_EXTRACTION_LIMIT = int(os.getenv('JOB_PROCESSING_EXTRACTION_LIMIT', 3))  # Parallel

# ==============================================================================
# STATS & ANALYTICS CONFIGURATION
# ==============================================================================

STATS_CONFIG = {
    'view_event_retention_days': 90,  # Keep ViewEvents for 90 days
    'enable_realtime_stats': True,    # Merge Redis data in queries
    'trending_decay_factor': 0.7,     # Weight for trending algorithm
}

# ==============================================================================
# DJANGO DEBUG TOOLBAR CONFIGURATION
# ==============================================================================

if DEBUG:
    INTERNAL_IPS = [
        "127.0.0.1",
        "localhost",
    ]

    # Debug Toolbar Panels
    DEBUG_TOOLBAR_PANELS = [
        'debug_toolbar.panels.history.HistoryPanel',
        'debug_toolbar.panels.versions.VersionsPanel',
        'debug_toolbar.panels.timer.TimerPanel',
        'debug_toolbar.panels.settings.SettingsPanel',
        'debug_toolbar.panels.headers.HeadersPanel',
        'debug_toolbar.panels.request.RequestPanel',
        'debug_toolbar.panels.sql.SQLPanel',
        'debug_toolbar.panels.staticfiles.StaticFilesPanel',
        'debug_toolbar.panels.templates.TemplatesPanel',
        'debug_toolbar.panels.cache.CachePanel',
        'debug_toolbar.panels.signals.SignalsPanel',
        'debug_toolbar.panels.redirects.RedirectsPanel',
        'debug_toolbar.panels.profiling.ProfilingPanel',
    ]

    # Debug Toolbar Config
    DEBUG_TOOLBAR_CONFIG = {
        'SHOW_TOOLBAR_CALLBACK': lambda request: DEBUG,
        'IS_RUNNING_TESTS': False,
    }

# ==============================================================================
# INTERNATIONALIZATION CONFIGURATION
# ==============================================================================

# Languages available for translation
LANGUAGES = [
    ('en', 'English'),
    ('zh-hans', 'Simplified Chinese'),
    ('zh-hant', 'Traditional Chinese'),
    ('ja', 'Japanese'),
    ('ko', 'Korean'),
    ('es', 'Spanish'),
    ('fr', 'French'),
]

# Locale paths for translations
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# Rosetta configuration
ROSETTA_SHOW_AT_ADMIN_PANEL = True
ROSETTA_ENABLE_TRANSLATION_SUGGESTIONS = False  # Set to True if you want Google Translate suggestions
