# Generated by Django 5.2.5 on 2025-11-20 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField(help_text='ID of the object this style applies to')),
                ('color', models.CharField(blank=True, default='', help_text="Primary color in hex format (e.g., '#FF5733')", max_length=7)),
                ('icon', models.CharField(blank=True, default='', help_text="FontAwesome icon class (e.g., 'fas fa-book')", max_length=50)),
                ('custom_styles', models.JSONField(blank=True, default=dict, help_text='Additional CSS properties: {font_weight, border_radius, hover_color, etc.}')),
                ('content_type', models.ForeignKey(help_text='Type of object this style applies to', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Style Configuration',
                'verbose_name_plural': 'Style Configurations',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='reader_styl_content_7860b5_idx')],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
