# Generated by Django 5.2.5 on 2025-11-20 20:41

from django.db import migrations


def migrate_section_styles(apps, schema_editor):
    """
    Copy icon field from Section to StyleConfig.

    This migration creates StyleConfig entries for all existing Sections
    that have an icon defined.

    Note: This is a no-op if icon field doesn't exist (already removed).
    """
    Section = apps.get_model('books', 'Section')
    StyleConfig = apps.get_model('reader', 'StyleConfig')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    # Get ContentType for Section model
    section_ct = ContentType.objects.get_for_model(Section)

    # Migrate each section's icon to StyleConfig (if field exists)
    for section in Section.objects.all():
        if hasattr(section, 'icon') and section.icon:  # Only create if field exists and has data
            StyleConfig.objects.create(
                content_type=section_ct,
                object_id=section.id,
                icon=section.icon,
                color='',  # Will be set manually or via seed command
                custom_styles={}
            )


def migrate_genre_styles(apps, schema_editor):
    """
    Copy icon and color fields from Genre to StyleConfig.

    This migration creates StyleConfig entries for all existing Genres
    that have an icon or color defined.

    Note: This is a no-op if icon/color fields don't exist (already removed).
    """
    Genre = apps.get_model('books', 'Genre')
    StyleConfig = apps.get_model('reader', 'StyleConfig')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    # Get ContentType for Genre model
    genre_ct = ContentType.objects.get_for_model(Genre)

    # Migrate each genre's icon and color to StyleConfig (if fields exist)
    for genre in Genre.objects.all():
        has_icon = hasattr(genre, 'icon')
        has_color = hasattr(genre, 'color')

        if (has_icon and genre.icon) or (has_color and genre.color):  # Create if either exists
            StyleConfig.objects.create(
                content_type=genre_ct,
                object_id=genre.id,
                icon=genre.icon if has_icon else '',
                color=genre.color if has_color else '',
                custom_styles={}
            )


def reverse_section_styles(apps, schema_editor):
    """
    Reverse migration: copy StyleConfig data back to Section.

    Note: This is a best-effort reverse. If Section fields are already
    removed, this will fail gracefully.
    """
    Section = apps.get_model('books', 'Section')
    StyleConfig = apps.get_model('reader', 'StyleConfig')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    try:
        section_ct = ContentType.objects.get_for_model(Section)

        for style in StyleConfig.objects.filter(content_type=section_ct):
            try:
                section = Section.objects.get(id=style.object_id)
                if hasattr(section, 'icon'):
                    section.icon = style.icon
                    section.save(update_fields=['icon'])
            except Section.DoesNotExist:
                pass
    except Exception:
        # Silently pass if fields don't exist anymore
        pass


def reverse_genre_styles(apps, schema_editor):
    """
    Reverse migration: copy StyleConfig data back to Genre.

    Note: This is a best-effort reverse. If Genre fields are already
    removed, this will fail gracefully.
    """
    Genre = apps.get_model('books', 'Genre')
    StyleConfig = apps.get_model('reader', 'StyleConfig')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    try:
        genre_ct = ContentType.objects.get_for_model(Genre)

        for style in StyleConfig.objects.filter(content_type=genre_ct):
            try:
                genre = Genre.objects.get(id=style.object_id)
                if hasattr(genre, 'icon'):
                    genre.icon = style.icon
                if hasattr(genre, 'color'):
                    genre.color = style.color
                genre.save(update_fields=['icon', 'color'])
            except Genre.DoesNotExist:
                pass
    except Exception:
        # Silently pass if fields don't exist anymore
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
        ('books', '0022_remove_genre_color_remove_genre_icon_and_more'),  # Depends on books app having Section/Genre
        ('contenttypes', '0002_remove_content_type_name'),  # Depends on ContentType framework
    ]

    operations = [
        migrations.RunPython(
            migrate_section_styles,
            reverse_code=reverse_section_styles
        ),
        migrations.RunPython(
            migrate_genre_styles,
            reverse_code=reverse_genre_styles
        ),
    ]
